# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 13:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('name_uk', models.CharField(db_index=True, max_length=25, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=25, null=True)),
                ('name_pl', models.CharField(db_index=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'verbose_name': 'Comment',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_news_img', models.ImageField(blank=True, upload_to='blog/posts/%Y/%m/%d')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, unique=True)),
                ('title_uk', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('title_pl', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_pl', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='blog_news.Category')),
            ],
            options={
                'verbose_name_plural': 'News in blog',
                'verbose_name': 'News in blog',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_news.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog_news.News'),
        ),
    ]
