# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 07:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='blog_news.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_news.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_pl',
            field=models.CharField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uk',
            field=models.CharField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
    ]
