# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 13:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
