# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0003_auto_20160902_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='blog_news_img',
            field=models.ImageField(blank=True, upload_to='blog/posts/%Y/%m/%d'),
        ),
    ]
