# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0004_auto_20160906_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=240, verbose_name='Subject')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Was Sand')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name_plural': 'Contacts',
                'verbose_name': 'Contact',
            },
        ),
    ]
