# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 20:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='content_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
