# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0007_auto_20160902_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_eng',
        ),
        migrations.AddField(
            model_name='news',
            name='title_pl',
            field=models.CharField(db_index=True, default=datetime.datetime(2016, 9, 2, 20, 23, 54, 271424, tzinfo=utc), max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(db_index=True, default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
